spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: customer-service
          uri: lb:http//CUSTOMER-SERVICE
          predicates:
            - Path=/protected/customer/**

        - id: order-service
          uri: lb:http//ORDER-SERVICE
          predicates:
            - Path=/protected/order/**

        - id: order-line-service
          uri: lb:http//ORDER-SERVICE
          predicates:
            - Path=/protected/orderLines/**

        - id: product-service
          uri: lb:http//PRODUCT-SERVICE
          predicates:
            - Path=/protected/product/**

        - id: payment-service
          uri: lb:http//PAYMENT-SERVICE
          predicates:
            - Path=/protected/payments/**

server:
  port: 8222
