spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_product
    username: ecom
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/protected/customer
    product-url: http://localhost:8222/protected/product
    payment-url: http://localhost:8222/protected/payment
